// Generated by scripts/write-stealth-extension.mjs from src/browser/stealth-signals.ts.
// Do not edit this file directly.

(() => {
  try {
    // Chrome exposes webdriver as an inherited accessor. Shadowing that accessor on this
    // Navigator instance makes the observed value undefined without changing unrelated APIs.
    Object.defineProperty(navigator, "webdriver", {
      configurable: true,
      get: () => undefined,
    });
  } catch {
    // Fingerprinting must never make a page unusable if a future browser disallows the shadow.
  }
})();
